AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  GetProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/libs/milhouse-api.jar
      Handler: com.confusedpenguins.nobodylikesmilhouse.api.host.profile.GetProfileHandler::handleRequest
      Runtime: java8
      Timeout: 15
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetProfileEvent:
          Type: Api
          Properties:
            Path: /profile
            Method: get
  UpdateProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/libs/milhouse-api.jar
      Handler: com.confusedpenguins.nobodylikesmilhouse.api.host.profile.UpdateProfileHandler::handleRequest
      Runtime: java8
      Timeout: 15
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetProfileEvent:
          Type: Api
          Properties:
            Path: /profile
            Method: post
  UserProfileTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "UserId"
            AttributeType: "S"
          - AttributeName: "ExternalId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "UserId"
            KeyType: "HASH"
          - AttributeName: "ExternalId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: UserProfiles